const mainTopics = [
    { label: '延伸與預修課程', value: 0 },
    { label: '課外閱讀', value: 1 },
    { label: '線上學習課程', value: 2 },
    { label: '能力檢定', value: 3 },
    { label: '服務學習課程', value: 4 },
    { label: '培訓課程', value: 5 },
    { label: '專題研究', value: 6 },
    { label: '其他', value: 7 },
];

const subTopics = [
    [
        { label: '延伸中文', value: 0 },
        { label: '延伸英文', value: 1 },
        { label: '延伸自然', value: 2 },
        { label: '延伸社會', value: 3 },
        { label: '延伸數學', value: 4 },
        { label: '延伸藝能', value: 5 },
    ],
    [
        { label: '課外中文', value: 0 },
        { label: '課外英文', value: 1 },
        { label: '課外數學', value: 2 },
        { label: '課外自然', value: 3 },
        { label: '課外社會', value: 4 },
        { label: '課外藝能', value: 5 },
    ],
    [
        { label: '線上大學平台課程', value: 0 },
        { label: '線上語文', value: 1 },
        { label: '線上數學', value: 2 },
        { label: '線上自然', value: 3 },
        { label: '線上社會', value: 4 },
        { label: '線上藝能台英聯盟', value: 5 },
    ],
    [
        { label: '資訊', value: 0 },
        { label: '英文', value: 1 },
        { label: '其他', value: 2 },
    ],
    [
        { label: '服務星嵐', value: 0 },
        { label: '服務星晞', value: 1 },
        { label: '服務公民科學家', value: 2 },
    ],
    [
        { label: '選手培訓', value: 0 },
        { label: '其他', value: 1 },
    ],
    [
        { label: '國文', value: 0 },
        { label: '英文', value: 1 },
        { label: '數學', value: 2 },
        { label: '物理', value: 3 },
        { label: '化學', value: 4 },
        { label: '生物', value: 5 },
        { label: '地科', value: 6 },
        { label: '資訊', value: 7 },
        { label: '生科', value: 8 },
        { label: '歷史', value: 9 },
        { label: '地理', value: 10 },
        { label: '公民', value: 11 },
        { label: '其他', value: 12 },
    ],
];

const classes = [
    { label: '101', value: 101 },
    { label: '102', value: 102 },
    { label: '103', value: 103 },
    { label: '104', value: 104 },
    { label: '105', value: 105 },
    { label: '106', value: 106 },
    { label: '107', value: 107 },
    { label: '108', value: 108 },
    { label: '109', value: 109 },
    { label: '110', value: 110 },
    { label: '111', value: 111 },
    { label: '201', value: 201 },
    { label: '202', value: 202 },
    { label: '203', value: 203 },
    { label: '204', value: 204 },
    { label: '205', value: 205 },
    { label: '206', value: 206 },
    { label: '207', value: 207 },
    { label: '208', value: 208 },
    { label: '209', value: 209 },
    { label: '210', value: 210 },
    { label: '211', value: 211 },
];

const numbers = [
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 },
    { label: '10', value: 10 },
    { label: '11', value: 11 },
    { label: '12', value: 12 },
    { label: '13', value: 13 },
    { label: '14', value: 14 },
    { label: '15', value: 15 },
    { label: '16', value: 16 },
    { label: '17', value: 17 },
    { label: '18', value: 18 },
    { label: '19', value: 19 },
    { label: '20', value: 20 },
    { label: '21', value: 21 },
    { label: '22', value: 22 },
    { label: '23', value: 23 },
    { label: '24', value: 24 },
    { label: '25', value: 25 },
    { label: '26', value: 26 },
    { label: '27', value: 27 },
    { label: '28', value: 28 },
    { label: '29', value: 29 },
    { label: '30', value: 30 },
];

const permit = [
    { label: '管理員', value: true },
    { label: '導師', value: false },
];

const exportClasses = [
    { label: '全部', value: 0 },
    { label: '101', value: 101 },
    { label: '102', value: 102 },
    { label: '103', value: 103 },
    { label: '104', value: 104 },
    { label: '105', value: 105 },
    { label: '106', value: 106 },
    { label: '107', value: 107 },
    { label: '108', value: 108 },
    { label: '109', value: 109 },
    { label: '110', value: 110 },
    { label: '111', value: 111 },
    { label: '201', value: 201 },
    { label: '202', value: 202 },
    { label: '203', value: 203 },
    { label: '204', value: 204 },
    { label: '205', value: 205 },
    { label: '206', value: 206 },
    { label: '207', value: 207 },
    { label: '208', value: 208 },
    { label: '209', value: 209 },
    { label: '210', value: 210 },
    { label: '211', value: 211 },
];

const teachers = [
    { label: '郭書毓', value: 201 },
    { label: '林學誼', value: 202 },
    { label: '范怡舒', value: 203 },
    { label: '廖悅淑', value: 204 },
    { label: '陳彥豪', value: 205 },
    { label: '江秀桂', value: 206 },
    { label: '盛寶徵', value: 207 },
    { label: '方湘儀', value: 208 },
    { label: '洪明譽', value: 209 },
    { label: '白偉民', value: 210 },
    { label: '謝采儒', value: 211 },
];

// eslint-disable-next-line
export { mainTopics, subTopics, classes, numbers, permit, exportClasses, teachers };
